### ISSUE TITLE
Feature Extraction

### ISSUE THREAD

**Issue by Chenghao-Ding** [mobarakol/Surgical_Graph#1]
Hi, I'm very interested in your work. Here are some issures when I use this code. The document in instrument_dataset.py {}_edge_features.npy is not found. I want to know how to generate this document. Could you add the Feature Extraction module in detail? Thanks very much!

**Comment by lalithjets** [comment]
Hi chenghao,

I have added a sample of the feature extractor. https://github.com/mobarakol/Surgical_SceneGraph_Generation/blob/main/feature_extractor.py

Thank you.

**Comment by Chenghao-Ding** [comment]
> Hi chenghao,
> 
> I have added a sample of the feature extractor. https://github.com/mobarakol/Surgical_SceneGraph_Generation/blob/main/feature_extractor.py
> 
> Thank you.

Hi, lalithjets. I have copy the roi_feature_model from the gpnn's code. There is another question when I run feature_extractor.py " node_features[roi_idx, ...] = feature.data.cpu().numpy()" 
AttributeError: 'tuple' object has no attribute 'data'
Do you know how to solve the problem? Thank you.
